// Generates src/web.ts: the browser entry of the contracts (`@jordan-sports/contracts/web`).
// Every endpoint becomes a plain { method, path, auth } object typed as the full endpoint, so the
// apps keep their typed calls while the bundle carries no zod schemas. Types come through
// `export type *` (erased at build time). Run after `pnpm build` whenever endpoints change:
//   pnpm --filter @jordan-sports/contracts gen:web       (writes)
//   node scripts/gen-web.mjs --check                     (fails if src/web.ts is stale)
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const contracts = await import(join(root, 'dist/index.js'));

const routes = Object.entries(contracts)
  .filter(([, v]) => v && typeof v === 'object' && 'method' in v && 'path' in v && 'response' in v)
  .sort(([a], [b]) => a.localeCompare(b));

const lines = [
  '// GENERATED by scripts/gen-web.mjs: do not edit. Regenerate after changing endpoints.',
  '/**',
  ' * Browser entry of the contracts: endpoint routes (method, path, auth) without their zod schemas,',
  ' * the zod-free API client, plain constants, and every type. Server code keeps using the full',
  ' * package (`@jordan-sports/contracts`), which validates requests and responses.',
  ' */',
  "import type * as C from './index.js';",
  '',
  "export type * from './index.js';",
  "export { ApiError, buildPath, createApiClient } from './client.js';",
  "export type { ApiClient, ApiClientOptions } from './client.js';",
  "export { errorCodes, LEGAL_TEXTS_VERSION, mediaWidths, venueRatingTags } from './constants.js';",
  "export { freeStarts } from './free-starts.js';",
  "export { GOVERNORATE_GEO, geoDistanceKm, governorateForPoint } from './geo.js';",
  '',
];
for (const [name, e] of routes) {
  const route = { method: e.method, path: e.path, auth: e.auth };
  lines.push(`export const ${name} = ${JSON.stringify(route)} as unknown as typeof C.${name};`);
}
const file = join(root, 'src/web.ts');
// Formatted like the rest of the repo, so `pnpm format:check` and --check agree.
const prettier = await import('prettier');
const text = await prettier.format(lines.join('\n') + '\n', {
  ...(await prettier.resolveConfig(file)),
  filepath: file,
});

if (process.argv.includes('--check')) {
  if (readFileSync(file, 'utf8') !== text) {
    console.error(
      'src/web.ts is out of date: run `pnpm --filter @jordan-sports/contracts gen:web`.',
    );
    process.exit(1);
  }
} else {
  writeFileSync(file, text);
  console.log(`src/web.ts: ${routes.length} routes`);
}
