-- 0010: fills in the areas the owner walked governorate-by-governorate (mostly Amman
-- neighborhoods plus more Irbid/Zarqa/Balqa detail). Deduped against 0008/0009 by matching
-- normalized Arabic name and English name (spelling variants like ta marbuta/hamza and
-- with/without the "ال" article are treated as the same place, so those are skipped here).

INSERT INTO catalog.areas (city_id, key, name, sort_order)
SELECT c.id, a.key, a.name::jsonb, a.sort_order FROM (VALUES
  ('amman', 'rabieh', '{"ar": "الرابية", "en": "Rabieh"}', 100),
  ('amman', '7th_circle', '{"ar": "الدوار السابع", "en": "7th Circle"}', 101),
  ('amman', '8th_circle', '{"ar": "الدوار الثامن", "en": "8th Circle"}', 102),
  ('amman', 'deir_ghbar', '{"ar": "دير غبار", "en": "Deir Ghbar"}', 103),
  ('amman', 'al_jamia', '{"ar": "الجامعة", "en": "Al-Jami''a"}', 104),
  ('amman', 'al_kursi', '{"ar": "الكرسي", "en": "Al-Kursi"}', 105),
  ('amman', 'al_bayader', '{"ar": "البيادر", "en": "Al-Bayader"}', 106),
  ('amman', 'abdali', '{"ar": "العبدلي", "en": "Abdali"}', 107),
  ('amman', 'weibdeh', '{"ar": "اللويبدة", "en": "Weibdeh"}', 108),
  ('amman', 'downtown', '{"ar": "وسط البلد", "en": "Downtown"}', 109),
  ('amman', 'gardens', '{"ar": "الجاردنز", "en": "Gardens"}', 110),
  ('amman', 'sports_city', '{"ar": "المدينة الرياضية", "en": "Sports City"}', 111),
  ('amman', 'mecca_street', '{"ar": "شارع مكة", "en": "Mecca Street"}', 112),
  ('amman', 'dahiyat_al_rasheed', '{"ar": "ضاحية الرشيد", "en": "Dahiyat Al-Rasheed"}', 113),
  ('amman', 'prince_rashid_suburb', '{"ar": "ضاحية الأمير راشد", "en": "Prince Rashid Suburb"}', 114),
  ('amman', 'dahiyat_al_yasmeen', '{"ar": "ضاحية الياسمين", "en": "Dahiyat Al-Yasmeen"}', 115),
  ('amman', 'abu_alanda', '{"ar": "أبو علندا", "en": "Abu Alanda"}', 116),
  ('amman', 'hashmi_al_shamali', '{"ar": "الهاشمي الشمالي", "en": "Hashmi Al-Shamali"}', 117),
  ('amman', 'jabal_al_nuzha', '{"ar": "جبل النزهة", "en": "Jabal Al-Nuzha"}', 118),
  ('amman', 'ashrafieh', '{"ar": "الأشرفية", "en": "Ashrafieh"}', 119),
  ('amman', 'al_muqabalain', '{"ar": "المقابلين", "en": "Al-Muqabalain"}', 120),
  ('amman', 'al_juwaideh', '{"ar": "الجويدة", "en": "Al-Juwaideh"}', 121),
  ('amman', 'al_yadudah', '{"ar": "اليادودة", "en": "Al-Yadudah"}', 122),
  ('amman', 'khraibet_al_souq', '{"ar": "خريبة السوق", "en": "Khraibet Al-Souq"}', 123),
  ('amman', 'al_bnayyat', '{"ar": "البنيات", "en": "Al-Bnayyat"}', 124),
  ('irbid', 'irbid_downtown', '{"ar": "وسط إربد", "en": "Irbid Downtown"}', 100),
  ('irbid', 'eastern_district', '{"ar": "الحي الشرقي", "en": "Eastern District"}', 101),
  ('irbid', 'southern_district', '{"ar": "الحي الجنوبي", "en": "Southern District"}', 102),
  ('irbid', 'thirty_street', '{"ar": "شارع الثلاثين", "en": "Thirty Street"}', 103),
  ('irbid', 'al_sareeh', '{"ar": "الصريح", "en": "Al-Sareeh"}', 104),
  ('irbid', 'al_nuaimeh', '{"ar": "النعيمة", "en": "Al-Nuaimeh"}', 105),
  ('irbid', 'huwwara', '{"ar": "حوارة", "en": "Huwwara"}', 106),
  ('irbid', 'kufr_yuba', '{"ar": "كفر يوبا", "en": "Kufr Yuba"}', 107),
  ('irbid', 'al_mashare', '{"ar": "المشارع", "en": "Al-Mashare''"}', 108),
  ('zarqa', 'zarqa_downtown', '{"ar": "وسط الزرقاء", "en": "Zarqa Downtown"}', 100),
  ('zarqa', 'hay_masoum', '{"ar": "حي معصوم", "en": "Hay Ma''soum"}', 101),
  ('zarqa', 'al_ghwairiyeh', '{"ar": "الغويرية", "en": "Al-Ghwairiyeh"}', 102),
  ('zarqa', 'jabal_al_amir_faisal', '{"ar": "جبل الأمير فيصل", "en": "Jabal Al-Amir Faisal"}', 103),
  ('zarqa', 'al_sukhneh', '{"ar": "السخنة", "en": "Al-Sukhneh"}', 104),
  ('balqa', 'baqaa', '{"ar": "البقعة", "en": "Baqa''a"}', 100),
  ('balqa', 'safut', '{"ar": "صافوط", "en": "Safut"}', 101),
  ('balqa', 'dead_sea', '{"ar": "البحر الميت", "en": "Dead Sea"}', 102),
  ('madaba', 'jreineh', '{"ar": "جرينة", "en": "Jreineh"}', 100),
  ('madaba', 'libb', '{"ar": "لب", "en": "Libb"}', 101),
  ('jerash', 'al_kitteh', '{"ar": "الكتة", "en": "Al-Kitteh"}', 100),
  ('jerash', 'dibbeen', '{"ar": "دبين", "en": "Dibbeen"}', 101),
  ('ajloun', 'sakhra', '{"ar": "صخرة", "en": "Sakhra"}', 100),
  ('ajloun', 'rason', '{"ar": "راسون", "en": "Rason"}', 101),
  ('mafraq', 'balama', '{"ar": "بلعما", "en": "Bal''ama"}', 100),
  ('mafraq', 'housha', '{"ar": "حوشا", "en": "Housha"}', 101),
  ('mafraq', 'sabha', '{"ar": "صبحا", "en": "Sabha"}', 102),
  ('karak', 'southern_jordan_valley', '{"ar": "الأغوار الجنوبية", "en": "Southern Jordan Valley"}', 100),
  ('tafilah', 'al_eis', '{"ar": "العيص", "en": "Al-Eis"}', 100),
  ('tafilah', 'ain_al_baida', '{"ar": "عين البيضاء", "en": "Ain Al-Baida"}', 101),
  ('maan', 'wadi_musa_petra', '{"ar": "وادي موسى (البتراء)", "en": "Wadi Musa (Petra)"}', 100),
  ('maan', 'al_jafr', '{"ar": "الجفر", "en": "Al-Jafr"}', 101),
  ('aqaba', 'ayla', '{"ar": "أيلة", "en": "Ayla"}', 100),
  ('aqaba', 'al_disi', '{"ar": "الديسة", "en": "Al-Disi"}', 101)
) AS a(city_key, key, name, sort_order)
JOIN catalog.cities c ON c.key = a.city_key;
