import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import * as full from '../src/index.js';
import * as web from '../src/web.js';

type Route = { method: string; path: string; auth: string };
const isEndpoint = (v: unknown): v is Route & { response: unknown } =>
  typeof v === 'object' && v !== null && 'method' in v && 'path' in v && 'response' in v;

/** The browser entry (src/web.ts, generated by scripts/gen-web.mjs) must mirror the contracts. */
describe('contracts/web', () => {
  it('has every endpoint with the same method, path and auth, and nothing else', () => {
    const endpoints = Object.entries(full).filter(([, v]) => isEndpoint(v)) as Array<
      [string, Route]
    >;
    const routes = Object.entries(web).filter(
      ([, v]) => typeof v === 'object' && v !== null && 'method' in v && 'path' in v,
    );
    expect(routes.map(([k]) => k).sort()).toEqual(endpoints.map(([k]) => k).sort());
    for (const [name, e] of endpoints) {
      const r = (web as unknown as Record<string, Route>)[name]!;
      expect({ name, ...r }).toEqual({ name, method: e.method, path: e.path, auth: e.auth });
      // No schemas in the browser bundle.
      expect('response' in r).toBe(false);
    }
  });

  it('pulls in no zod at runtime', () => {
    for (const file of ['web.ts', 'client.ts', 'constants.ts', 'free-starts.ts', 'geo.ts']) {
      const src = readFileSync(join(__dirname, '../src', file), 'utf8');
      expect(src, file).not.toMatch(
        /^import (?!type)[^;]*from '(zod|\.\/(?!client|constants|free-starts|geo)[^']+)'/m,
      );
    }
  });

  it('keeps the shared constants identical', () => {
    expect(web.errorCodes).toBe(full.errorCodes);
    expect(web.LEGAL_TEXTS_VERSION).toBe(full.LEGAL_TEXTS_VERSION);
  });
});
