// GENERATED by scripts/gen-web.mjs: do not edit. Regenerate after changing endpoints.
/**
 * Browser entry of the contracts: endpoint routes (method, path, auth) without their zod schemas,
 * the zod-free API client, plain constants, and every type. Server code keeps using the full
 * package (`@jordan-sports/contracts`), which validates requests and responses.
 */
import type * as C from './index.js';

export type * from './index.js';
export { ApiError, buildPath, createApiClient } from './client.js';
export type { ApiClient, ApiClientOptions } from './client.js';
export { errorCodes, LEGAL_TEXTS_VERSION, mediaWidths, venueRatingTags } from './constants.js';
export { freeStarts } from './free-starts.js';

export const addVenueTeamMember = {
  method: 'POST',
  path: '/v1/manage/venues/:venueId/team',
  auth: 'user',
} as unknown as typeof C.addVenueTeamMember;
export const adminAddMember = {
  method: 'POST',
  path: '/v1/admin/organizations/:organizationId/members',
  auth: 'admin',
} as unknown as typeof C.adminAddMember;
export const adminArchiveVenue = {
  method: 'POST',
  path: '/v1/admin/venues/:venueId/archive',
  auth: 'admin',
} as unknown as typeof C.adminArchiveVenue;
export const adminCancelBooking = {
  method: 'POST',
  path: '/v1/admin/bookings/:bookingId/cancel',
  auth: 'admin',
} as unknown as typeof C.adminCancelBooking;
export const adminChangeStaffRole = {
  method: 'PUT',
  path: '/v1/admin/team/:userId/role',
  auth: 'admin',
} as unknown as typeof C.adminChangeStaffRole;
export const adminCreateArea = {
  method: 'POST',
  path: '/v1/admin/geography/governorates/:governorateId/areas',
  auth: 'admin',
} as unknown as typeof C.adminCreateArea;
export const adminCreateFacility = {
  method: 'POST',
  path: '/v1/admin/venues/:venueId/facilities',
  auth: 'admin',
} as unknown as typeof C.adminCreateFacility;
export const adminCreateGovernorate = {
  method: 'POST',
  path: '/v1/admin/geography/governorates',
  auth: 'admin',
} as unknown as typeof C.adminCreateGovernorate;
export const adminCreateHoliday = {
  method: 'POST',
  path: '/v1/admin/holidays',
  auth: 'admin',
} as unknown as typeof C.adminCreateHoliday;
export const adminCreateOrganization = {
  method: 'POST',
  path: '/v1/admin/organizations',
  auth: 'admin',
} as unknown as typeof C.adminCreateOrganization;
export const adminCreateResource = {
  method: 'POST',
  path: '/v1/admin/venues/:venueId/resources',
  auth: 'admin',
} as unknown as typeof C.adminCreateResource;
export const adminCreateSport = {
  method: 'POST',
  path: '/v1/admin/sports',
  auth: 'admin',
} as unknown as typeof C.adminCreateSport;
export const adminCreateVenue = {
  method: 'POST',
  path: '/v1/admin/organizations/:organizationId/venues',
  auth: 'admin',
} as unknown as typeof C.adminCreateVenue;
export const adminDeleteHoliday = {
  method: 'DELETE',
  path: '/v1/admin/holidays/:holidayId',
  auth: 'admin',
} as unknown as typeof C.adminDeleteHoliday;
export const adminDeleteVenueMedia = {
  method: 'DELETE',
  path: '/v1/admin/media/:mediaId',
  auth: 'admin',
} as unknown as typeof C.adminDeleteVenueMedia;
export const adminExportAuditLogs = {
  method: 'GET',
  path: '/v1/admin/audit-logs.csv',
  auth: 'admin',
} as unknown as typeof C.adminExportAuditLogs;
export const adminExportBookings = {
  method: 'GET',
  path: '/v1/admin/reports/bookings.csv',
  auth: 'admin',
} as unknown as typeof C.adminExportBookings;
export const adminExportUserData = {
  method: 'GET',
  path: '/v1/admin/users/:userId/export',
  auth: 'admin',
} as unknown as typeof C.adminExportUserData;
export const adminGetBooking = {
  method: 'GET',
  path: '/v1/admin/bookings/:bookingId',
  auth: 'admin',
} as unknown as typeof C.adminGetBooking;
export const adminGetComplaint = {
  method: 'GET',
  path: '/v1/admin/complaints/:complaintId',
  auth: 'admin',
} as unknown as typeof C.adminGetComplaint;
export const adminGetOrganization = {
  method: 'GET',
  path: '/v1/admin/organizations/:organizationId',
  auth: 'admin',
} as unknown as typeof C.adminGetOrganization;
export const adminGetSettings = {
  method: 'GET',
  path: '/v1/admin/settings',
  auth: 'admin',
} as unknown as typeof C.adminGetSettings;
export const adminGetTeam = {
  method: 'GET',
  path: '/v1/admin/team',
  auth: 'admin',
} as unknown as typeof C.adminGetTeam;
export const adminGetUser = {
  method: 'GET',
  path: '/v1/admin/users/:userId',
  auth: 'admin',
} as unknown as typeof C.adminGetUser;
export const adminGetVenue = {
  method: 'GET',
  path: '/v1/admin/venues/:venueId',
  auth: 'admin',
} as unknown as typeof C.adminGetVenue;
export const adminGetVenueRating = {
  method: 'GET',
  path: '/v1/admin/venues/:venueId/rating',
  auth: 'admin',
} as unknown as typeof C.adminGetVenueRating;
export const adminGetVenueReviewSummary = {
  method: 'GET',
  path: '/v1/admin/venues/:venueId/review-summary',
  auth: 'admin',
} as unknown as typeof C.adminGetVenueReviewSummary;
export const adminGetVenueStats = {
  method: 'GET',
  path: '/v1/admin/venues/:venueId/stats',
  auth: 'admin',
} as unknown as typeof C.adminGetVenueStats;
export const adminInviteStaff = {
  method: 'POST',
  path: '/v1/admin/team/invitations',
  auth: 'admin',
} as unknown as typeof C.adminInviteStaff;
export const adminListAuditLogs = {
  method: 'GET',
  path: '/v1/admin/audit-logs',
  auth: 'admin',
} as unknown as typeof C.adminListAuditLogs;
export const adminListBookings = {
  method: 'GET',
  path: '/v1/admin/bookings',
  auth: 'admin',
} as unknown as typeof C.adminListBookings;
export const adminListComplaints = {
  method: 'GET',
  path: '/v1/admin/complaints',
  auth: 'admin',
} as unknown as typeof C.adminListComplaints;
export const adminListHolidays = {
  method: 'GET',
  path: '/v1/admin/holidays',
  auth: 'admin',
} as unknown as typeof C.adminListHolidays;
export const adminListOrganizations = {
  method: 'GET',
  path: '/v1/admin/organizations',
  auth: 'admin',
} as unknown as typeof C.adminListOrganizations;
export const adminListPayouts = {
  method: 'GET',
  path: '/v1/admin/payouts',
  auth: 'admin',
} as unknown as typeof C.adminListPayouts;
export const adminListPendingVenues = {
  method: 'GET',
  path: '/v1/admin/venues',
  auth: 'admin',
} as unknown as typeof C.adminListPendingVenues;
export const adminListSports = {
  method: 'GET',
  path: '/v1/admin/sports',
  auth: 'admin',
} as unknown as typeof C.adminListSports;
export const adminListTransactions = {
  method: 'GET',
  path: '/v1/admin/payments/transactions',
  auth: 'admin',
} as unknown as typeof C.adminListTransactions;
export const adminListUsers = {
  method: 'GET',
  path: '/v1/admin/users',
  auth: 'admin',
} as unknown as typeof C.adminListUsers;
export const adminListVenues = {
  method: 'GET',
  path: '/v1/admin/organizations/:organizationId/venues',
  auth: 'admin',
} as unknown as typeof C.adminListVenues;
export const adminMarkPayoutPaid = {
  method: 'POST',
  path: '/v1/admin/venues/:venueId/payouts',
  auth: 'admin',
} as unknown as typeof C.adminMarkPayoutPaid;
export const adminRateVenue = {
  method: 'POST',
  path: '/v1/admin/venues/:venueId/rating',
  auth: 'admin',
} as unknown as typeof C.adminRateVenue;
export const adminReauth = {
  method: 'POST',
  path: '/v1/admin/auth/reauth',
  auth: 'admin',
} as unknown as typeof C.adminReauth;
export const adminRemoveStaff = {
  method: 'DELETE',
  path: '/v1/admin/team/:userId',
  auth: 'admin',
} as unknown as typeof C.adminRemoveStaff;
export const adminReplyToComplaint = {
  method: 'POST',
  path: '/v1/admin/complaints/:complaintId/messages',
  auth: 'admin',
} as unknown as typeof C.adminReplyToComplaint;
export const adminReportsOverview = {
  method: 'GET',
  path: '/v1/admin/reports/overview',
  auth: 'admin',
} as unknown as typeof C.adminReportsOverview;
export const adminRetryRefund = {
  method: 'POST',
  path: '/v1/admin/payments/refunds/:transactionId/retry',
  auth: 'admin',
} as unknown as typeof C.adminRetryRefund;
export const adminRevokeInvitation = {
  method: 'DELETE',
  path: '/v1/admin/team/invitations/:invitationId',
  auth: 'admin',
} as unknown as typeof C.adminRevokeInvitation;
export const adminSetUserStatus = {
  method: 'POST',
  path: '/v1/admin/users/:userId/status',
  auth: 'admin',
} as unknown as typeof C.adminSetUserStatus;
export const adminSetVenueCommission = {
  method: 'PUT',
  path: '/v1/admin/venues/:venueId/commission',
  auth: 'admin',
} as unknown as typeof C.adminSetVenueCommission;
export const adminSetVenueStatus = {
  method: 'POST',
  path: '/v1/admin/venues/:venueId/status',
  auth: 'admin',
} as unknown as typeof C.adminSetVenueStatus;
export const adminSignIn = {
  method: 'POST',
  path: '/v1/admin/auth/sign-in',
  auth: 'public',
} as unknown as typeof C.adminSignIn;
export const adminSignOut = {
  method: 'POST',
  path: '/v1/admin/auth/sign-out',
  auth: 'public',
} as unknown as typeof C.adminSignOut;
export const adminUpdateArea = {
  method: 'PATCH',
  path: '/v1/admin/geography/areas/:areaId',
  auth: 'admin',
} as unknown as typeof C.adminUpdateArea;
export const adminUpdateComplaint = {
  method: 'PATCH',
  path: '/v1/admin/complaints/:complaintId',
  auth: 'admin',
} as unknown as typeof C.adminUpdateComplaint;
export const adminUpdateGovernorate = {
  method: 'PATCH',
  path: '/v1/admin/geography/governorates/:governorateId',
  auth: 'admin',
} as unknown as typeof C.adminUpdateGovernorate;
export const adminUpdateResource = {
  method: 'PATCH',
  path: '/v1/admin/resources/:resourceId',
  auth: 'admin',
} as unknown as typeof C.adminUpdateResource;
export const adminUpdateSettings = {
  method: 'PATCH',
  path: '/v1/admin/settings',
  auth: 'admin',
} as unknown as typeof C.adminUpdateSettings;
export const adminUpdateSport = {
  method: 'PATCH',
  path: '/v1/admin/sports/:sportId',
  auth: 'admin',
} as unknown as typeof C.adminUpdateSport;
export const adminUpdateVenue = {
  method: 'PATCH',
  path: '/v1/admin/venues/:venueId',
  auth: 'admin',
} as unknown as typeof C.adminUpdateVenue;
export const adminUploadVenueMedia = {
  method: 'POST',
  path: '/v1/admin/venues/:venueId/media',
  auth: 'admin',
} as unknown as typeof C.adminUploadVenueMedia;
export const archiveOwnVenue = {
  method: 'POST',
  path: '/v1/manage/venues/:venueId/archive',
  auth: 'user',
} as unknown as typeof C.archiveOwnVenue;
export const archivePriceRule = {
  method: 'DELETE',
  path: '/v1/manage/price-rules/:ruleId',
  auth: 'user',
} as unknown as typeof C.archivePriceRule;
export const cancelBlock = {
  method: 'DELETE',
  path: '/v1/manage/blocks/:blockId',
  auth: 'user',
} as unknown as typeof C.cancelBlock;
export const cancelBooking = {
  method: 'POST',
  path: '/v1/bookings/:bookingId/cancel',
  auth: 'user',
} as unknown as typeof C.cancelBooking;
export const cancelMockCheckout = {
  method: 'POST',
  path: '/v1/mock-gateway/sessions/:sessionId/cancel',
  auth: 'public',
} as unknown as typeof C.cancelMockCheckout;
export const cancelVenueBooking = {
  method: 'POST',
  path: '/v1/manage/bookings/:bookingId/cancel',
  auth: 'user',
} as unknown as typeof C.cancelVenueBooking;
export const changeVenueTeamRole = {
  method: 'PUT',
  path: '/v1/manage/members/:memberId',
  auth: 'user',
} as unknown as typeof C.changeVenueTeamRole;
export const checkInBooking = {
  method: 'POST',
  path: '/v1/manage/bookings/:bookingId/check-in',
  auth: 'user',
} as unknown as typeof C.checkInBooking;
export const completeAccountSetup = {
  method: 'POST',
  path: '/v1/admin/setup/complete',
  auth: 'public',
} as unknown as typeof C.completeAccountSetup;
export const completeSignup = {
  method: 'POST',
  path: '/v1/auth/signup',
  auth: 'public',
} as unknown as typeof C.completeSignup;
export const createBlock = {
  method: 'POST',
  path: '/v1/manage/venues/:venueId/blocks',
  auth: 'user',
} as unknown as typeof C.createBlock;
export const createBookingHold = {
  method: 'POST',
  path: '/v1/bookings',
  auth: 'user',
} as unknown as typeof C.createBookingHold;
export const createManualBooking = {
  method: 'POST',
  path: '/v1/manage/venues/:venueId/bookings',
  auth: 'user',
} as unknown as typeof C.createManualBooking;
export const createMyFacility = {
  method: 'POST',
  path: '/v1/manage/venues/:venueId/facilities',
  auth: 'user',
} as unknown as typeof C.createMyFacility;
export const createMyResource = {
  method: 'POST',
  path: '/v1/manage/venues/:venueId/resources',
  auth: 'user',
} as unknown as typeof C.createMyResource;
export const createOverride = {
  method: 'POST',
  path: '/v1/manage/venues/:venueId/overrides',
  auth: 'user',
} as unknown as typeof C.createOverride;
export const createPriceRules = {
  method: 'POST',
  path: '/v1/manage/venues/:venueId/pricing',
  auth: 'user',
} as unknown as typeof C.createPriceRules;
export const deleteMyAccount = {
  method: 'POST',
  path: '/v1/me/delete',
  auth: 'user',
} as unknown as typeof C.deleteMyAccount;
export const deleteMyVenueMedia = {
  method: 'DELETE',
  path: '/v1/manage/media/:mediaId',
  auth: 'user',
} as unknown as typeof C.deleteMyVenueMedia;
export const deleteOverride = {
  method: 'DELETE',
  path: '/v1/manage/overrides/:overrideId',
  auth: 'user',
} as unknown as typeof C.deleteOverride;
export const getAdminMe = {
  method: 'GET',
  path: '/v1/admin/me',
  auth: 'admin',
} as unknown as typeof C.getAdminMe;
export const getBooking = {
  method: 'GET',
  path: '/v1/bookings/:bookingId',
  auth: 'user',
} as unknown as typeof C.getBooking;
export const getCatalog = {
  method: 'GET',
  path: '/v1/catalog',
  auth: 'public',
} as unknown as typeof C.getCatalog;
export const getMe = { method: 'GET', path: '/v1/me', auth: 'user' } as unknown as typeof C.getMe;
export const getMockCheckout = {
  method: 'GET',
  path: '/v1/mock-gateway/sessions/:sessionId',
  auth: 'public',
} as unknown as typeof C.getMockCheckout;
export const getMyVenueProfile = {
  method: 'GET',
  path: '/v1/manage/venues/:venueId/profile',
  auth: 'user',
} as unknown as typeof C.getMyVenueProfile;
export const getPayoutAccount = {
  method: 'GET',
  path: '/v1/manage/venues/:venueId/payout-account',
  auth: 'user',
} as unknown as typeof C.getPayoutAccount;
export const getVenue = {
  method: 'GET',
  path: '/v1/venues/:slug',
  auth: 'public',
} as unknown as typeof C.getVenue;
export const getVenueAvailability = {
  method: 'GET',
  path: '/v1/venues/:slug/availability',
  auth: 'public',
} as unknown as typeof C.getVenueAvailability;
export const getVenueCalendar = {
  method: 'GET',
  path: '/v1/manage/venues/:venueId/calendar',
  auth: 'user',
} as unknown as typeof C.getVenueCalendar;
export const getVenueEarnings = {
  method: 'GET',
  path: '/v1/manage/venues/:venueId/earnings',
  auth: 'user',
} as unknown as typeof C.getVenueEarnings;
export const getVenuePricing = {
  method: 'GET',
  path: '/v1/manage/venues/:venueId/pricing',
  auth: 'user',
} as unknown as typeof C.getVenuePricing;
export const getVenueSchedule = {
  method: 'GET',
  path: '/v1/manage/venues/:venueId/schedule',
  auth: 'user',
} as unknown as typeof C.getVenueSchedule;
export const getVenueStats = {
  method: 'GET',
  path: '/v1/manage/venues/:venueId/stats',
  auth: 'user',
} as unknown as typeof C.getVenueStats;
export const inspectAccountSetup = {
  method: 'POST',
  path: '/v1/admin/setup/inspect',
  auth: 'public',
} as unknown as typeof C.inspectAccountSetup;
export const listManagedVenues = {
  method: 'GET',
  path: '/v1/manage/venues',
  auth: 'user',
} as unknown as typeof C.listManagedVenues;
export const listMyBookings = {
  method: 'GET',
  path: '/v1/me/bookings',
  auth: 'user',
} as unknown as typeof C.listMyBookings;
export const listMyComplaints = {
  method: 'GET',
  path: '/v1/me/complaints',
  auth: 'user',
} as unknown as typeof C.listMyComplaints;
export const listVenueBookings = {
  method: 'GET',
  path: '/v1/manage/venues/:venueId/bookings',
  auth: 'user',
} as unknown as typeof C.listVenueBookings;
export const listVenues = {
  method: 'GET',
  path: '/v1/venues',
  auth: 'public',
} as unknown as typeof C.listVenues;
export const listVenueTeam = {
  method: 'GET',
  path: '/v1/manage/venues/:venueId/team',
  auth: 'user',
} as unknown as typeof C.listVenueTeam;
export const markNoShow = {
  method: 'POST',
  path: '/v1/manage/bookings/:bookingId/no-show',
  auth: 'user',
} as unknown as typeof C.markNoShow;
export const payMockCheckout = {
  method: 'POST',
  path: '/v1/mock-gateway/sessions/:sessionId/pay',
  auth: 'public',
} as unknown as typeof C.payMockCheckout;
export const previewQuote = {
  method: 'GET',
  path: '/v1/manage/resources/:resourceId/quote',
  auth: 'user',
} as unknown as typeof C.previewQuote;
export const registerVenue = {
  method: 'POST',
  path: '/v1/manage/venues',
  auth: 'user',
} as unknown as typeof C.registerVenue;
export const removeVenueTeamMember = {
  method: 'DELETE',
  path: '/v1/manage/members/:memberId',
  auth: 'user',
} as unknown as typeof C.removeVenueTeamMember;
export const reorderMyVenueMedia = {
  method: 'PUT',
  path: '/v1/manage/venues/:venueId/media/order',
  auth: 'user',
} as unknown as typeof C.reorderMyVenueMedia;
export const replacePriceRule = {
  method: 'PUT',
  path: '/v1/manage/price-rules/:ruleId',
  auth: 'user',
} as unknown as typeof C.replacePriceRule;
export const replyToMyComplaint = {
  method: 'POST',
  path: '/v1/me/complaints/:complaintId/messages',
  auth: 'user',
} as unknown as typeof C.replyToMyComplaint;
export const reportProblem = {
  method: 'POST',
  path: '/v1/me/complaints',
  auth: 'user',
} as unknown as typeof C.reportProblem;
export const reportVenueProblem = {
  method: 'POST',
  path: '/v1/manage/venues/:venueId/complaints',
  auth: 'user',
} as unknown as typeof C.reportVenueProblem;
export const requestOtp = {
  method: 'POST',
  path: '/v1/auth/otp/request',
  auth: 'public',
} as unknown as typeof C.requestOtp;
export const setBookingPolicy = {
  method: 'PUT',
  path: '/v1/manage/resources/:resourceId/policy',
  auth: 'user',
} as unknown as typeof C.setBookingPolicy;
export const setPayoutAccount = {
  method: 'PUT',
  path: '/v1/manage/venues/:venueId/payout-account',
  auth: 'user',
} as unknown as typeof C.setPayoutAccount;
export const setWeeklyHours = {
  method: 'PUT',
  path: '/v1/manage/resources/:resourceId/weekly-hours',
  auth: 'user',
} as unknown as typeof C.setWeeklyHours;
export const signOut = {
  method: 'POST',
  path: '/v1/auth/sign-out',
  auth: 'public',
} as unknown as typeof C.signOut;
export const startCheckout = {
  method: 'POST',
  path: '/v1/bookings/:bookingId/checkout',
  auth: 'user',
} as unknown as typeof C.startCheckout;
export const submitMyVenue = {
  method: 'POST',
  path: '/v1/manage/venues/:venueId/submit',
  auth: 'user',
} as unknown as typeof C.submitMyVenue;
export const updateMe = {
  method: 'PATCH',
  path: '/v1/me',
  auth: 'user',
} as unknown as typeof C.updateMe;
export const updateMyResource = {
  method: 'PATCH',
  path: '/v1/manage/resources/:resourceId',
  auth: 'user',
} as unknown as typeof C.updateMyResource;
export const updateMyVenue = {
  method: 'PATCH',
  path: '/v1/manage/venues/:venueId',
  auth: 'user',
} as unknown as typeof C.updateMyVenue;
export const updateScheduleSettings = {
  method: 'PATCH',
  path: '/v1/manage/venues/:venueId/settings',
  auth: 'user',
} as unknown as typeof C.updateScheduleSettings;
export const uploadMyVenueMedia = {
  method: 'POST',
  path: '/v1/manage/venues/:venueId/media',
  auth: 'user',
} as unknown as typeof C.uploadMyVenueMedia;
export const verifyCheckout = {
  method: 'POST',
  path: '/v1/bookings/:bookingId/checkout/verify',
  auth: 'user',
} as unknown as typeof C.verifyCheckout;
export const verifyOtp = {
  method: 'POST',
  path: '/v1/auth/otp/verify',
  auth: 'public',
} as unknown as typeof C.verifyOtp;
