/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditAuditLogs {
  action: string;
  actor_type: string;
  actor_user_id: string | null;
  details: Generated<Json>;
  id: string;
  ip: string | null;
  occurred_at: Generated<Timestamp>;
  organization_id: string | null;
  reason: string | null;
  request_id: string | null;
  target_id: string | null;
  target_type: string | null;
  user_agent: string | null;
}

export interface BookingBookingItems {
  amount: Int8 | null;
  booking_id: string;
  during: string;
  id: string;
  resource_id: string;
}

export interface BookingBookings {
  business_date: string;
  cancel_reason: string | null;
  cancellation_policy: Json;
  cancelled_at: Timestamp | null;
  cancelled_by: string | null;
  cancelled_by_role: string | null;
  channel: string;
  checked_in_at: Timestamp | null;
  checked_in_by: string | null;
  commission_bps: number | null;
  confirmed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  currency: string;
  customer_user_id: string | null;
  during: string;
  hold_expires_at: Timestamp | null;
  id: string;
  late_cancellation: boolean | null;
  note: string | null;
  organization_id: string;
  payment_method: string | null;
  payment_status: string;
  price_snapshot: Json | null;
  reference: string;
  resource_id: string;
  series_id: string | null;
  status: string;
  subtotal: Int8 | null;
  time_zone: string;
  total: Int8 | null;
  updated_at: Generated<Timestamp>;
  venue_customer_id: string | null;
  venue_id: string;
}

export interface BookingSeries {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  duration_minutes: number;
  first_date: string;
  id: string;
  resource_id: string;
  start_time: string;
  venue_customer_id: string;
  venue_id: string;
  weeks: number;
}

export interface BookingStatusHistory {
  actor_type: string;
  actor_user_id: string | null;
  booking_id: string;
  from_status: string | null;
  id: string;
  occurred_at: Generated<Timestamp>;
  reason: string | null;
  to_status: string;
}

export interface BookingVenueCustomers {
  created_at: Generated<Timestamp>;
  id: string;
  name: string;
  organization_id: string;
  phone: string | null;
}

export interface CatalogAmenities {
  id: Generated<string>;
  key: string;
  name: Json;
  sort_order: Generated<number>;
}

export interface CatalogAreas {
  city_id: string;
  id: Generated<string>;
  key: string;
  name: Json;
  sort_order: Generated<number>;
}

export interface CatalogCities {
  country_code: string;
  id: Generated<string>;
  key: string;
  name: Json;
  sort_order: Generated<number>;
  timezone: string;
}

export interface CatalogResourceTypeFormats {
  resource_type_id: string;
  sport_format_id: string;
}

export interface CatalogResourceTypes {
  active: Generated<boolean>;
  attribute_schema: Generated<Json>;
  id: Generated<string>;
  key: string;
  name: Json;
  sort_order: Generated<number>;
}

export interface CatalogSportFormats {
  active: Generated<boolean>;
  default_duration_minutes: number;
  id: Generated<string>;
  key: string;
  max_players: number;
  min_players: number;
  name: Json;
  sort_order: Generated<number>;
  sport_id: string;
}

export interface CatalogSportRequests {
  created_at: Generated<Timestamp>;
  id: string;
  name: string;
  note: string | null;
  organization_id: string;
  rejection_reason: string | null;
  requested_by: string | null;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
  resolved_sport_id: string | null;
  status: Generated<string>;
}

export interface CatalogSports {
  active: Generated<boolean>;
  icon: Generated<string>;
  id: Generated<string>;
  key: string;
  name: Json;
  sort_order: Generated<number>;
}

export interface FinanceBalanceEntries {
  amount: Int8;
  balance_after: Int8;
  booking_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  currency: string;
  id: string;
  kind: string;
  organization_id: string;
  reason: string | null;
}

export interface FinanceBalances {
  balance: Generated<Int8>;
  currency: Generated<string>;
  organization_id: string;
  updated_at: Generated<Timestamp>;
}

export interface FinancePayoutAccounts {
  bank_name: string | null;
  holder_name: string;
  iban: string;
  organization_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface FinancePayoutItems {
  booking_id: string;
  commission: Int8;
  gross: Int8;
  net: Int8;
  payout_id: string;
}

export interface FinancePayouts {
  commission: Int8;
  currency: string;
  gross: Int8;
  iban: string;
  id: string;
  net: Int8;
  organization_id: string;
  paid_at: Generated<Timestamp>;
  paid_by: string;
  reference: string;
  venue_id: string;
}

export interface IdentityAccountSetupTokens {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  display_name: string | null;
  email: string;
  expires_at: Timestamp;
  id: string;
  platform_role: string;
  purpose: string;
  replace_owner: Generated<boolean>;
  revoked_at: Timestamp | null;
  token_hash: string;
  totp_secret_encrypted: string;
  used_at: Timestamp | null;
}

export interface IdentityOtpChallenges {
  attempts: Generated<number>;
  code_hash: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  phone: string;
  signup_completed_at: Timestamp | null;
  signup_token_hash: string | null;
  verified_at: Timestamp | null;
}

export interface IdentityPasswordCredentials {
  password_hash: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface IdentitySessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  ip: string | null;
  kind: string;
  last_seen_at: Generated<Timestamp>;
  reauthenticated_at: Timestamp | null;
  revoked_at: Timestamp | null;
  token_hash: string;
  user_agent: string | null;
  user_id: string;
}

export interface IdentityStaffDevices {
  device_hash: string;
  first_seen_at: Generated<Timestamp>;
  last_seen_at: Generated<Timestamp>;
  user_agent: string | null;
  user_id: string;
}

export interface IdentityTotpCredentials {
  created_at: Generated<Timestamp>;
  last_used_step: Generated<Int8>;
  secret_encrypted: string;
  user_id: string;
}

export interface IdentityUsers {
  age_confirmed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  display_name: string | null;
  email: string | null;
  failed_sign_ins: Generated<number>;
  id: string;
  locale: Generated<string>;
  locked_until: Timestamp | null;
  phone: string | null;
  platform_role: string | null;
  preferred_mode: Generated<string>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface NotificationDeliveries {
  body: string;
  channel: string;
  created_at: Generated<Timestamp>;
  event_id: string;
  id: string;
  locale: string;
  recipient: string;
  status: string;
  template: string;
}

export interface PaymentDisputes {
  booking_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  kind: string;
  opened_by_role: string;
  organization_id: string;
  payment_id: string | null;
  resolution: string | null;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
  status: Generated<string>;
  venue_id: string;
}

export interface PaymentPayments {
  amount: Int8;
  booking_id: string;
  confirmed_at: Timestamp | null;
  confirmed_by: string | null;
  created_at: Generated<Timestamp>;
  currency: string;
  id: string;
  organization_id: string;
  payee_alias: string;
  payee_holder: string | null;
  provider: string;
  reference: string | null;
  reference_key: string | null;
  refund_due_at: Timestamp | null;
  refund_status: string | null;
  refunded_at: Timestamp | null;
  refunded_by: string | null;
  reject_reason: string | null;
  rejected_at: Timestamp | null;
  rejected_by: string | null;
  status: string;
  submitted_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
  venue_id: string;
}

export interface PaymentTransactions {
  amount: Int8;
  attempts: Generated<number>;
  booking_id: string;
  card_brand: string | null;
  card_last4: string | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  currency: string;
  failure_code: string | null;
  gateway: string;
  gateway_ref: string | null;
  id: string;
  kind: string;
  organization_id: string;
  reason: string | null;
  status: string;
  updated_at: Generated<Timestamp>;
  venue_id: string;
}

export interface PlatformIdempotencyKeys {
  created_at: Generated<Timestamp>;
  key: string;
  request_hash: string;
  response_body: Json | null;
  response_status: number | null;
  status: string;
  user_id: string;
}

export interface PlatformOutboxEvents {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  id: string;
  last_error: string | null;
  next_attempt_at: Generated<Timestamp>;
  payload: Json;
  processed_at: Timestamp | null;
  type: string;
}

export interface PlatformSettings {
  admin_ip_allowlist: Generated<string[]>;
  commission_bps: Generated<number>;
  features: Generated<Json>;
  id: Generated<boolean>;
  support_email: string | null;
  support_whatsapp: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  venue_edits_need_review: Generated<boolean>;
}

export interface PlatformVenueRatings {
  created_at: Generated<Timestamp>;
  created_by: string;
  id: string;
  note: string | null;
  score: number;
  tags: Generated<string[]>;
  venue_id: string;
}

export interface PricingPriceRuleAmounts {
  amount: Int8;
  duration_minutes: number;
  rule_id: string;
}

export interface PricingPriceRules {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  currency: string;
  date_from: string | null;
  date_to: string | null;
  days_of_week: number[];
  end_minute: number;
  id: string;
  label: string | null;
  priority: Generated<number>;
  resource_id: string;
  start_minute: number;
  venue_id: string;
}

export interface ResourceBookingPolicies {
  buffer_after_minutes: Generated<number>;
  buffer_before_minutes: Generated<number>;
  hold_minutes: Generated<number>;
  max_advance_days: Generated<number>;
  min_lead_minutes: Generated<number>;
  resource_id: string;
  slot_durations: number[];
  start_alignment_minutes: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface ResourceResourceFormats {
  resource_id: string;
  sport_format_id: string;
}

export interface ResourceResources {
  attributes: Generated<Json>;
  created_at: Generated<Timestamp>;
  facility_id: string | null;
  id: string;
  name: Json;
  resource_type_id: string;
  sort_order: Generated<number>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  venue_id: string;
}

export interface ResourceResourceUnits {
  resource_id: string;
  unit_id: string;
}

export interface ResourceUnits {
  created_at: Generated<Timestamp>;
  id: string;
  venue_id: string;
}

export interface SchedulingBlocks {
  cancelled_at: Timestamp | null;
  cancelled_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  during: string;
  id: string;
  note: string | null;
  reason: string;
  resource_id: string;
  venue_id: string;
}

export interface SchedulingDateOverrides {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  date_from: string;
  date_to: string;
  id: string;
  kind: string;
  note: string | null;
  resource_id: string | null;
  venue_id: string;
  windows: Generated<Json>;
}

export interface SchedulingHolidays {
  country_code: string;
  date: string;
  id: string;
  name: Json;
}

export interface SchedulingOccupancies {
  active: Generated<boolean>;
  block_id: string | null;
  booking_id: string | null;
  created_at: Generated<Timestamp>;
  during: string;
  expires_at: Timestamp | null;
  id: string;
  kind: string;
  unit_id: string;
  venue_id: string;
}

export interface SchedulingWeeklyHours {
  created_at: Generated<Timestamp>;
  day_of_week: number;
  duration_minutes: number;
  id: string;
  resource_id: string;
  start_minute: number;
}

export interface SupportComplaintMessages {
  author_kind: string;
  author_user_id: string;
  body: string;
  complaint_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  internal: Generated<boolean>;
}

export interface SupportComplaints {
  assignee_id: string | null;
  body: string;
  booking_id: string | null;
  category: string;
  created_at: Generated<Timestamp>;
  id: string;
  organization_id: string | null;
  reference: string;
  reporter_kind: string;
  reporter_user_id: string;
  resolved_at: Timestamp | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  venue_id: string | null;
}

export interface TenancyMemberships {
  created_at: Generated<Timestamp>;
  id: string;
  organization_id: string;
  role: string;
  user_id: string;
}

export interface TenancyOrganizations {
  created_at: Generated<Timestamp>;
  id: string;
  name: Json;
  slug: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface VenueFacilities {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: string;
  name: Json;
  sort_order: Generated<number>;
  venue_id: string;
}

export interface VenueMedia {
  blur: string | null;
  byte_size: number;
  content_type: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  height: number;
  id: string;
  sort_order: Generated<number>;
  storage_key: string;
  venue_id: string;
  width: number;
}

export interface VenueVenueAmenities {
  amenity_id: string;
  venue_id: string;
}

export interface VenueVenues {
  address: Generated<Json>;
  archived_at: Timestamp | null;
  area_id: string | null;
  business_day_start_minute: Generated<number>;
  cancellation_cutoff_hours: Generated<number>;
  city_id: string;
  cliq_alias: string | null;
  cliq_alias_holder: string | null;
  closed_on_public_holidays: Generated<boolean>;
  commission_bps: number | null;
  contact_phone: string | null;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  deposit_percentage: number | null;
  description: Generated<Json>;
  id: string;
  late_refund_percent: Generated<number>;
  location: string | null;
  name: Json;
  organization_id: string;
  payment_hold_minutes: Generated<number>;
  slug: string;
  status: Generated<string>;
  status_reason: string | null;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
  whatsapp_phone: string | null;
}

export interface DB {
  'audit.audit_logs': AuditAuditLogs;
  'booking.booking_items': BookingBookingItems;
  'booking.bookings': BookingBookings;
  'booking.series': BookingSeries;
  'booking.status_history': BookingStatusHistory;
  'booking.venue_customers': BookingVenueCustomers;
  'catalog.amenities': CatalogAmenities;
  'catalog.areas': CatalogAreas;
  'catalog.cities': CatalogCities;
  'catalog.resource_type_formats': CatalogResourceTypeFormats;
  'catalog.resource_types': CatalogResourceTypes;
  'catalog.sport_formats': CatalogSportFormats;
  'catalog.sport_requests': CatalogSportRequests;
  'catalog.sports': CatalogSports;
  'finance.balance_entries': FinanceBalanceEntries;
  'finance.balances': FinanceBalances;
  'finance.payout_accounts': FinancePayoutAccounts;
  'finance.payout_items': FinancePayoutItems;
  'finance.payouts': FinancePayouts;
  'identity.account_setup_tokens': IdentityAccountSetupTokens;
  'identity.otp_challenges': IdentityOtpChallenges;
  'identity.password_credentials': IdentityPasswordCredentials;
  'identity.sessions': IdentitySessions;
  'identity.staff_devices': IdentityStaffDevices;
  'identity.totp_credentials': IdentityTotpCredentials;
  'identity.users': IdentityUsers;
  'notification.deliveries': NotificationDeliveries;
  'payment.disputes': PaymentDisputes;
  'payment.payments': PaymentPayments;
  'payment.transactions': PaymentTransactions;
  'platform.idempotency_keys': PlatformIdempotencyKeys;
  'platform.outbox_events': PlatformOutboxEvents;
  'platform.settings': PlatformSettings;
  'platform.venue_ratings': PlatformVenueRatings;
  'pricing.price_rule_amounts': PricingPriceRuleAmounts;
  'pricing.price_rules': PricingPriceRules;
  'resource.booking_policies': ResourceBookingPolicies;
  'resource.resource_formats': ResourceResourceFormats;
  'resource.resource_units': ResourceResourceUnits;
  'resource.resources': ResourceResources;
  'resource.units': ResourceUnits;
  'scheduling.blocks': SchedulingBlocks;
  'scheduling.date_overrides': SchedulingDateOverrides;
  'scheduling.holidays': SchedulingHolidays;
  'scheduling.occupancies': SchedulingOccupancies;
  'scheduling.weekly_hours': SchedulingWeeklyHours;
  'support.complaint_messages': SupportComplaintMessages;
  'support.complaints': SupportComplaints;
  'tenancy.memberships': TenancyMemberships;
  'tenancy.organizations': TenancyOrganizations;
  'venue.facilities': VenueFacilities;
  'venue.media': VenueMedia;
  'venue.venue_amenities': VenueVenueAmenities;
  'venue.venues': VenueVenues;
}
