/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditAuditLogs {
  action: string;
  actor_type: string;
  actor_user_id: string | null;
  details: Generated<Json>;
  id: string;
  ip: string | null;
  occurred_at: Generated<Timestamp>;
  organization_id: string | null;
  reason: string | null;
  request_id: string | null;
  target_id: string | null;
  target_type: string | null;
  user_agent: string | null;
}

export interface CatalogAmenities {
  id: Generated<string>;
  key: string;
  name: Json;
  sort_order: Generated<number>;
}

export interface CatalogAreas {
  city_id: string;
  id: Generated<string>;
  key: string;
  name: Json;
  sort_order: Generated<number>;
}

export interface CatalogCities {
  country_code: string;
  id: Generated<string>;
  key: string;
  name: Json;
  sort_order: Generated<number>;
  timezone: string;
}

export interface CatalogResourceTypeFormats {
  resource_type_id: string;
  sport_format_id: string;
}

export interface CatalogResourceTypes {
  active: Generated<boolean>;
  attribute_schema: Generated<Json>;
  id: Generated<string>;
  key: string;
  name: Json;
  sort_order: Generated<number>;
}

export interface CatalogSportFormats {
  active: Generated<boolean>;
  default_duration_minutes: number;
  id: Generated<string>;
  key: string;
  max_players: number;
  min_players: number;
  name: Json;
  sort_order: Generated<number>;
  sport_id: string;
}

export interface CatalogSports {
  active: Generated<boolean>;
  id: Generated<string>;
  key: string;
  name: Json;
  sort_order: Generated<number>;
}

export interface IdentityOtpChallenges {
  attempts: Generated<number>;
  code_hash: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  phone: string;
  signup_completed_at: Timestamp | null;
  signup_token_hash: string | null;
  verified_at: Timestamp | null;
}

export interface IdentityPasswordCredentials {
  password_hash: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface IdentitySessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  ip: string | null;
  kind: string;
  last_seen_at: Generated<Timestamp>;
  revoked_at: Timestamp | null;
  token_hash: string;
  user_agent: string | null;
  user_id: string;
}

export interface IdentityTotpCredentials {
  created_at: Generated<Timestamp>;
  last_used_step: Generated<Int8>;
  secret_encrypted: string;
  user_id: string;
}

export interface IdentityUsers {
  age_confirmed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  display_name: string | null;
  email: string | null;
  id: string;
  locale: Generated<string>;
  phone: string | null;
  platform_role: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface ResourceBookingPolicies {
  buffer_after_minutes: Generated<number>;
  buffer_before_minutes: Generated<number>;
  hold_minutes: Generated<number>;
  max_advance_days: Generated<number>;
  min_lead_minutes: Generated<number>;
  resource_id: string;
  slot_durations: number[];
  start_alignment_minutes: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface ResourceResourceFormats {
  resource_id: string;
  sport_format_id: string;
}

export interface ResourceResources {
  attributes: Generated<Json>;
  created_at: Generated<Timestamp>;
  facility_id: string | null;
  id: string;
  name: Json;
  resource_type_id: string;
  sort_order: Generated<number>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  venue_id: string;
}

export interface ResourceResourceUnits {
  resource_id: string;
  unit_id: string;
}

export interface ResourceUnits {
  created_at: Generated<Timestamp>;
  id: string;
  venue_id: string;
}

export interface SchedulingBlocks {
  cancelled_at: Timestamp | null;
  cancelled_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  during: string;
  id: string;
  note: string | null;
  reason: string;
  resource_id: string;
  venue_id: string;
}

export interface SchedulingDateOverrides {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  date_from: string;
  date_to: string;
  id: string;
  kind: string;
  note: string | null;
  resource_id: string | null;
  venue_id: string;
  windows: Generated<Json>;
}

export interface SchedulingHolidays {
  country_code: string;
  date: string;
  id: string;
  name: Json;
}

export interface SchedulingOccupancies {
  active: Generated<boolean>;
  block_id: string | null;
  booking_id: string | null;
  created_at: Generated<Timestamp>;
  during: string;
  expires_at: Timestamp | null;
  id: string;
  kind: string;
  unit_id: string;
  venue_id: string;
}

export interface SchedulingWeeklyHours {
  created_at: Generated<Timestamp>;
  day_of_week: number;
  duration_minutes: number;
  id: string;
  resource_id: string;
  start_minute: number;
}

export interface TenancyMemberships {
  created_at: Generated<Timestamp>;
  id: string;
  organization_id: string;
  role: string;
  user_id: string;
}

export interface TenancyOrganizations {
  created_at: Generated<Timestamp>;
  id: string;
  name: Json;
  slug: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface VenueFacilities {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: string;
  name: Json;
  sort_order: Generated<number>;
  venue_id: string;
}

export interface VenueMedia {
  byte_size: number;
  content_type: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  height: number;
  id: string;
  sort_order: Generated<number>;
  storage_key: string;
  venue_id: string;
  width: number;
}

export interface VenueVenueAmenities {
  amenity_id: string;
  venue_id: string;
}

export interface VenueVenues {
  address: Generated<Json>;
  archived_at: Timestamp | null;
  area_id: string | null;
  business_day_start_minute: Generated<number>;
  city_id: string;
  closed_on_public_holidays: Generated<boolean>;
  contact_phone: string | null;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  description: Generated<Json>;
  id: string;
  location: string | null;
  name: Json;
  organization_id: string;
  slug: string;
  status: Generated<string>;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  'audit.audit_logs': AuditAuditLogs;
  'catalog.amenities': CatalogAmenities;
  'catalog.areas': CatalogAreas;
  'catalog.cities': CatalogCities;
  'catalog.resource_type_formats': CatalogResourceTypeFormats;
  'catalog.resource_types': CatalogResourceTypes;
  'catalog.sport_formats': CatalogSportFormats;
  'catalog.sports': CatalogSports;
  'identity.otp_challenges': IdentityOtpChallenges;
  'identity.password_credentials': IdentityPasswordCredentials;
  'identity.sessions': IdentitySessions;
  'identity.totp_credentials': IdentityTotpCredentials;
  'identity.users': IdentityUsers;
  'resource.booking_policies': ResourceBookingPolicies;
  'resource.resource_formats': ResourceResourceFormats;
  'resource.resource_units': ResourceResourceUnits;
  'resource.resources': ResourceResources;
  'resource.units': ResourceUnits;
  'scheduling.blocks': SchedulingBlocks;
  'scheduling.date_overrides': SchedulingDateOverrides;
  'scheduling.holidays': SchedulingHolidays;
  'scheduling.occupancies': SchedulingOccupancies;
  'scheduling.weekly_hours': SchedulingWeeklyHours;
  'tenancy.memberships': TenancyMemberships;
  'tenancy.organizations': TenancyOrganizations;
  'venue.facilities': VenueFacilities;
  'venue.media': VenueMedia;
  'venue.venue_amenities': VenueVenueAmenities;
  'venue.venues': VenueVenues;
}
